#!/bin/bash
##
 # @name            jPulse Framework / Deploy / Install System
 # @tagline         Install system for jPulse site
 # @description     This script will install the system for jPulse site
 #                  - Run as root: sudo ./deploy/install-system.sh
 #                  - Generated by jpulse-setup for Red Hat Enterprise Linux
 # @site            %SITE_NAME%
 # @generated       %GENERATION_DATE%
 # @file            templates/deploy/install-system.sh
 # @version         0.6.8
 # @release         2025-09-13
 # @repository      https://github.com/peterthoeny/jpulse-framework
 # @author          Peter Thoeny, https://twiki.org & https://github.com/peterthoeny/
 # @copyright       2025 Peter Thoeny, https://twiki.org & https://github.com/peterthoeny/
 # @license         AGPL v3, see LICENSE file
 # @genai           95%, Cursor 1.2, Claude Sonnet 4
##

set -e

# Security check - must run as root
if [ "$EUID" -ne 0 ]; then
    echo "❌ SECURITY ERROR: This script must run as root"
    echo "💡 Run with: sudo ./deploy/install-system.sh"
    exit 1
fi

# Platform check
if ! command -v dnf >/dev/null 2>&1 && ! command -v yum >/dev/null 2>&1; then
    echo "❌ PLATFORM ERROR: Red Hat Enterprise Linux required"
    echo "💡 Supported: RHEL, Rocky Linux, CentOS, Fedora"
    exit 1
fi

echo "🔧 jPulse System Installation (Red Hat Enterprise Linux)"
echo "======================================================"
echo ""
echo "Site: %SITE_NAME%"
echo "Platform: $(cat /etc/redhat-release)"
echo "User: root"
echo ""
echo "This script will install:"
echo "  1. Node.js 18 LTS"
echo "  2. MongoDB 6.0"
echo "  3. nginx"
echo "  4. PM2 process manager"
echo "  5. Configure firewall"
echo "  6. Create application user"
echo ""

read -p "🤔 Proceed with system installation? (y/N): " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Installation cancelled"
    exit 1
fi

# Install Node.js (NodeSource repository)
echo "📦 Installing Node.js 18 LTS..."
if ! command -v node >/dev/null 2>&1; then
    curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
    dnf install -y nodejs
    echo "✅ Node.js installed: $(node --version)"
else
    echo "✅ Node.js already installed: $(node --version)"
fi

# Install MongoDB
echo "📦 Installing MongoDB..."
if ! command -v mongosh >/dev/null 2>&1; then
    cat > /etc/yum.repos.d/mongodb-org-6.0.repo << EOF
[mongodb-org-6.0]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/8/mongodb-org/6.0/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-6.0.asc
EOF

    dnf install -y mongodb-org
    echo "✅ MongoDB installed"
else
    echo "✅ MongoDB already installed"
fi

# Install nginx
echo "📦 Installing nginx..."
if ! command -v nginx >/dev/null 2>&1; then
    dnf install -y nginx
    echo "✅ nginx installed"
else
    echo "✅ nginx already installed"
fi

# Install PM2 globally
echo "📦 Installing PM2..."
if ! command -v pm2 >/dev/null 2>&1; then
    npm install -g pm2
    echo "✅ PM2 installed: $(pm2 --version)"
else
    echo "✅ PM2 already installed: $(pm2 --version)"
fi

# Application user setup
echo "👤 Setting up application user..."
echo ""
echo "You can either:"
echo "  1) Use existing user (admin/service account)"
echo "  2) Create new dedicated 'jpulse' user"
echo ""
read -p "? Create new 'jpulse' user? (y/N): " CREATE_USER
CREATE_USER=${CREATE_USER:-n}

if [[ "$CREATE_USER" =~ ^[Yy] ]]; then
    if ! id "jpulse" &>/dev/null; then
        useradd -r -s /bin/bash -d /opt/jpulse -m jpulse
        echo "✅ Application user 'jpulse' created"
        APP_USER="jpulse"
    else
        echo "✅ Application user 'jpulse' already exists"
        APP_USER="jpulse"
    fi
else
    echo "ℹ️  Using existing user for application deployment"
    echo "💡 Ensure your user has access to:"
    echo "   - /opt/ directory (for application files)"
    echo "   - /var/log/ directory (for log files)"
    echo "   - PM2 and MongoDB commands"
    APP_USER=$(whoami)
    echo "✅ Will use current user for deployment guidance"
fi

# Create log directory
echo "📁 Creating log directories..."
mkdir -p /var/log/jpulse
if [[ "$APP_USER" == "jpulse" ]]; then
    chown jpulse:jpulse /var/log/jpulse
else
    # For existing users, make logs writable by the user's group
    chown root:$(id -gn $APP_USER) /var/log/jpulse
    chmod 775 /var/log/jpulse
fi
echo "✅ Log directory created: /var/log/jpulse"

# Configure firewall
echo "🔥 Configuring firewall..."
if systemctl is-active --quiet firewalld; then
    firewall-cmd --permanent --add-service=http
    firewall-cmd --permanent --add-service=https
    firewall-cmd --permanent --add-port=%APP_PORT%/tcp
    firewall-cmd --reload
    echo "✅ Firewall configured (HTTP, HTTPS, port %APP_PORT%)"
else
    echo "⚠️  Firewall not active - manual configuration required"
fi

# Start and enable services
echo "🚀 Starting services..."
systemctl enable --now mongod
systemctl enable --now nginx

echo ""
echo "✅ System installation complete!"
echo ""
echo "📋 Installation Summary:"
echo "   Node.js: $(node --version)"
echo "   MongoDB: Installed and running"
echo "   nginx: Installed and running"
echo "   PM2: $(pm2 --version)"
echo "   Application user: $APP_USER"
echo "   Log directory: /var/log/jpulse"
echo ""
echo "💡 Next steps:"
if [[ "$APP_USER" == "jpulse" ]]; then
    echo "   1. Switch to application user: sudo -u jpulse -i"
    echo "   2. Deploy application to /opt/jpulse/"
else
    echo "   1. Deploy application to your preferred directory"
    echo "   2. Ensure $APP_USER has access to /var/log/jpulse/"
fi
echo "   3. Run database setup: ./deploy/mongodb-setup.sh"
echo "   4. Configure nginx: ./deploy/setup-nginx.sh"
echo "   5. Start application: pm2 start deploy/ecosystem.prod.config.js"

# EOF deploy/install-system.sh
