#!/bin/bash
##
 # @name            jPulse Framework / Deploy / MongoDB Setup
 # @tagline         MongoDB setup for jPulse site
 # @description     This script will setup MongoDB for jPulse site
 #                  - Run as application user: ./deploy/mongodb-setup.sh
 #                  - Generated by jpulse-setup for Red Hat Enterprise Linux
 # @site            %SITE_NAME%
 # @generated       %GENERATION_DATE%
 # @file            templates/deploy/mongodb-setup.sh
 # @version         0.6.9
 # @release         2025-09-14
 # @repository      https://github.com/peterthoeny/jpulse-framework
 # @author          Peter Thoeny, https://twiki.org & https://github.com/peterthoeny/
 # @copyright       2025 Peter Thoeny, https://twiki.org & https://github.com/peterthoeny/
 # @license         AGPL v3, see LICENSE file
 # @genai           95%, Cursor 1.2, Claude Sonnet 4
##

set -e

# Security check - must NOT run as root
if [ "$EUID" -eq 0 ]; then
    echo "❌ SECURITY ERROR: Do not run this script as root!"
    echo "💡 Run as application user: ./deploy/mongodb-setup.sh"
    exit 1
fi

# Platform check - Red Hat ecosystem only
if ! command -v dnf >/dev/null 2>&1 && ! command -v yum >/dev/null 2>&1; then
    echo "❌ PLATFORM ERROR: This script is for Red Hat Enterprise Linux ecosystem"
    echo "💡 Supported: RHEL, Rocky Linux, CentOS, Fedora"
    exit 1
fi

echo "🗄️  jPulse MongoDB Setup (Red Hat Enterprise Linux)"
echo "=================================================="
echo ""
echo "Site: %SITE_NAME%"
echo "Platform: $(cat /etc/redhat-release 2>/dev/null || echo 'Red Hat Compatible')"
echo "User: $(whoami)"
echo ""
echo "This script will:"
echo "  1. Create MongoDB admin user (if not exists)"
echo "  2. Create application database: %DB_NAME%"
echo "  3. Create application user: %DB_USER%"
echo ""

# Check if MongoDB is running
if ! systemctl is-active --quiet mongod; then
    echo "❌ MongoDB is not running."
    echo "💡 Start MongoDB first: sudo systemctl start mongod"
    exit 1
fi

# Environment variables check
if [ -z "$DB_ADMIN_PASS" ] || [ -z "$DB_PASS" ]; then
    echo "❌ Required environment variables not set:"
    echo ""
    echo "   export DB_ADMIN_PASS='<your-admin-password>'"
    echo "   export DB_USER='%DB_USER%'"
    echo "   export DB_PASS='<your-app-password>'"
    echo "   export DB_NAME='%DB_NAME%'"
    echo ""
    echo "💡 Copy from .env file: source .env"
    echo "💡 Or set variables: export DB_ADMIN_PASS='your-password'"
    exit 1
fi

# Check if admin user already exists
echo "🔍 Checking existing MongoDB configuration..."
if mongosh admin --eval "db.getUser('%DB_ADMIN_USER%')" --quiet 2>/dev/null | grep -q "%DB_ADMIN_USER%"; then
    echo "✅ Admin user already exists"
    SKIP_ADMIN=true
else
    echo "📝 Admin user needs to be created"
    SKIP_ADMIN=false
fi

# Check if app user already exists
if mongosh "%DB_NAME%" --eval "db.getUser('$DB_USER')" --quiet 2>/dev/null | grep -q "$DB_USER"; then
    echo "✅ App user '$DB_USER' already exists"
    SKIP_APP=true
else
    echo "📝 App user '$DB_USER' needs to be created"
    SKIP_APP=false
fi

if [ "$SKIP_ADMIN" = true ] && [ "$SKIP_APP" = true ]; then
    echo ""
    echo "✅ MongoDB already configured for jPulse"
    echo "🚀 Ready to start application!"
    exit 0
fi

echo ""
read -p "🤔 Proceed with MongoDB setup? (y/N): " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Setup cancelled"
    exit 1
fi

# Setup admin user (if needed)
if [ "$SKIP_ADMIN" = false ]; then
    echo "👤 Creating MongoDB admin user..."
    mongosh admin --eval "
        db.createUser({
            user: '%DB_ADMIN_USER%',
            pwd: '$DB_ADMIN_PASS',
            roles: ['userAdminAnyDatabase', 'dbAdminAnyDatabase']
        })
    "
    echo "✅ Admin user created"
fi

# Setup app user and database
echo "🗄️  Creating application database '$DB_NAME' and user '$DB_USER'..."
mongosh admin -u %DB_ADMIN_USER% -p "$DB_ADMIN_PASS" --eval "
    use $DB_NAME;
    db.createUser({
        user: '$DB_USER',
        pwd: '$DB_PASS',
        roles: [
            {role: 'readWrite', db: '$DB_NAME'},
            {role: 'dbAdmin', db: '$DB_NAME'}
        ]
    });

    // Create initial collection to ensure database exists
    db.system_info.insertOne({
        created: new Date(),
        version: '1.0.0',
        framework: 'jPulse',
        site: '%SITE_NAME%'
    });
"

echo ""
# Create initial admin user for jPulse application
echo ""
echo "👤 Creating initial admin user for jPulse application..."
echo ""

# Prompt for admin user details
read -p "? Admin username ($(whoami)): " ADMIN_USERNAME
ADMIN_USERNAME=${ADMIN_USERNAME:-$(whoami)}

read -p "? Admin first name: " ADMIN_FIRST_NAME
while [ -z "$ADMIN_FIRST_NAME" ]; do
    read -p "? Admin first name (required): " ADMIN_FIRST_NAME
done

read -p "? Admin last name: " ADMIN_LAST_NAME
while [ -z "$ADMIN_LAST_NAME" ]; do
    read -p "? Admin last name (required): " ADMIN_LAST_NAME
done

read -p "? Admin email ($ADMIN_USERNAME@%DOMAIN_NAME%): " ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-$ADMIN_USERNAME@%DOMAIN_NAME%}

# Prompt for admin password
echo ""
read -s -p "? Admin password: " ADMIN_PASSWORD
echo ""
while [ -z "$ADMIN_PASSWORD" ]; do
    read -s -p "? Admin password (required): " ADMIN_PASSWORD
    echo ""
done

read -s -p "? Confirm admin password: " ADMIN_PASSWORD_CONFIRM
echo ""
while [ "$ADMIN_PASSWORD" != "$ADMIN_PASSWORD_CONFIRM" ]; do
    echo "❌ Passwords do not match"
    read -s -p "? Admin password: " ADMIN_PASSWORD
    echo ""
    read -s -p "? Confirm admin password: " ADMIN_PASSWORD_CONFIRM
    echo ""
done

# Generate UUID for the user (simple timestamp-based)
ADMIN_UUID="admin-$(date +%s)-$(whoami)"

# Escape special characters in password for safe JavaScript usage
# Replace single quotes with escaped single quotes and wrap in single quotes
ADMIN_PASSWORD_ESCAPED=$(printf '%s\n' "$ADMIN_PASSWORD" | sed "s/'/'\\\\''/g")

# Create the admin user document
echo "🔐 Creating admin user in database..."
mongosh "$DB_NAME" -u "$DB_USER" -p "$DB_PASS" --eval "
// Hash the password using a simple method (in production, jPulse will use bcrypt)
const crypto = require('crypto');
const saltRounds = 10;
const salt = crypto.randomBytes(16).toString('hex');
const adminPassword = '$ADMIN_PASSWORD_ESCAPED';
const hash = crypto.pbkdf2Sync(adminPassword, salt, 1000, 64, 'sha512').toString('hex');
const passwordHash = salt + ':' + hash;

const adminUser = {
    username: '$ADMIN_USERNAME',
    uuid: '$ADMIN_UUID',
    email: '$ADMIN_EMAIL',
    passwordHash: passwordHash,
    profile: {
        firstName: '$ADMIN_FIRST_NAME',
        lastName: '$ADMIN_LAST_NAME',
        nickName: '',
        avatar: ''
    },
    roles: ['admin'],
    preferences: {
        language: 'en',
        theme: 'light'
    },
    status: 'active',
    lastLogin: null,
    loginCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    updatedBy: 'mongodb-setup',
    docVersion: 1,
    saveCount: 1
};

// Check if user already exists
const existingUser = db.users.findOne({username: '$ADMIN_USERNAME'});
if (existingUser) {
    print('⚠️  Admin user already exists: $ADMIN_USERNAME');
} else {
    const result = db.users.insertOne(adminUser);
    if (result.acknowledged) {
        print('✅ Admin user created: $ADMIN_USERNAME');
    } else {
        print('❌ Failed to create admin user');
    }
}
" --quiet

echo "✅ MongoDB setup complete!"
echo ""
echo "📋 Configuration Summary:"
echo "   Database: $DB_NAME"
echo "   App User: $DB_USER"
echo "   Admin User: %DB_ADMIN_USER%"
echo "   jPulse Admin: $ADMIN_USERNAME ($ADMIN_EMAIL)"
echo ""
echo "💡 Next steps:"
echo "   1. Verify .env file contains correct credentials"
echo "   2. Start jPulse application: npm start"
echo "   3. Login with admin user: $ADMIN_USERNAME"
echo "   4. Check application logs for database connection"

# EOF deploy/mongodb-setup.sh
